import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { TRANSMISSIONS } from "../transmissions/catalog.mjs";
import { SESSION_SCHEMA, buildSession, cleanVoices, suggestTransmission } from "../transmissions/runtime.mjs";
const root = new URL("../transmissions/", import.meta.url);

test("7 Transmissions publishes exactly seven independent modes", () => { assert.equal(TRANSMISSIONS.length,7); assert.equal(new Set(TRANSMISSIONS.map(item=>item.id)).size,7); assert.deepEqual(TRANSMISSIONS.map(item=>item.id),["TX1","TX2","TX3","TX4","TX5","TX6","TX7"]); });
test("literal suggestion is deterministic and defaults to Resonance", () => { assert.equal(suggestTransmission("Нужно выпустить результат в срок").id,"TX5"); assert.equal(suggestTransmission("Пока неясно").id,"TX3"); });
test("session records explicit voice gate and never infers consent", () => { const draft={object:"Выпуск нового продукта",tension:"Нужно собрать общий шаг",voices:"Анна\nБорис\nАнна",txId:"TX3",voiceTrace:"Оба голоса предъявили различия",nextStep:"Собрать единый макет",owner:"Анна",window:"завтра",voiceGate:"not-presented"}; const session=buildSession(draft,TRANSMISSIONS,{now:()=>"2026-07-20T00:00:00.000Z",uuid:()=>"tx-test"}); assert.equal(session.schema,SESSION_SCHEMA); assert.deepEqual(cleanVoices(draft.voices),["Анна","Борис"]); assert.equal(session.outcome,"hold"); assert.match(session.boundary,/silence is never treated as consent/); });
test("release is local-first and self-contained", async()=>{const [html,app,css,sw]=await Promise.all([readFile(new URL("index.html",root),"utf8"),readFile(new URL("app.mjs",root),"utf8"),readFile(new URL("styles.css",root),"utf8"),readFile(new URL("../sw.js",root),"utf8")]);assert.match(html,/7 TRANSMISSIONS · STABLE RELEASE 1\.0/);assert.doesNotMatch(html,/https?:\/\//);assert.match(app,/localStorage\.setItem/);assert.match(app,/serviceWorker\.register\("\.\.\/sw\.js"\)/);for(const file of ["transmissions/index.html","transmissions/styles.css","transmissions/app.mjs","transmissions/catalog.mjs","transmissions/runtime.mjs"])assert.match(sw,new RegExp(file.replace(/[.*+?^${}()|[\]\\]/g,"\\$&"),"u"));assert.match(css,/-webkit-appearance:none/);});
