import { TRANSMISSIONS } from "./catalog.mjs";
import { buildSession, cleanVoices, suggestTransmission, validateSession } from "./runtime.mjs";

const STORAGE_KEY = "architectonica.reson.transmissions.v1";
const state = { object:"", tension:"", voices:"", txId:"", voiceTrace:"", nextStep:"", owner:"", window:"", voiceGate:"", session:null, suggestion:null };
const $ = selector => document.querySelector(selector); const $$ = selector => [...document.querySelectorAll(selector)];
const escapeHtml = value => String(value).replace(/[&<>"']/g, character => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"})[character]);
const words = value => String(value || "").trim().split(/\s+/u).filter(Boolean).length;
function readJournal(){try{const value=JSON.parse(localStorage.getItem(STORAGE_KEY)||"[]");return Array.isArray(value)?value:[]}catch{return[]}}
function updateJournal(){ $("#journal-count").textContent=String(readJournal().length) }
function save(session){localStorage.setItem(STORAGE_KEY,JSON.stringify([session,...readJournal()].slice(0,100)));updateJournal()}
function setStage(name){const order=["field","deck","practice","result"],index=order.indexOf(name);$$('[data-stage]').forEach(section=>{const active=section.dataset.stage===name;section.classList.toggle("active",active);section.setAttribute("aria-hidden",String(!active))});$$('.steps button').forEach((button,i)=>button.classList.toggle("active",i<=index));window.scrollTo({top:Math.max(0,$(".workspace").offsetTop-18),behavior:"smooth"})}
function syncField(){state.object=$("#shared-object").value.trim();state.tension=$("#tension").value.trim();state.voices=$("#voices").value.trim()}
function validateField(){syncField();const voices=cleanVoices(state.voices),valid=words(state.object)>=3&&words(state.tension)>=3&&voices.length>=2;$("#suggest").disabled=!valid;$("#open-deck").disabled=!valid;$("#field-hint").textContent=voices.length+" голосов · "+(words(state.object)>=3?"объект назван":"назовите общий объект")+" · "+(words(state.tension)>=3?"напряжение предъявлено":"предъявите напряжение")}
function renderDeck(){$("#deck").innerHTML=TRANSMISSIONS.map(item=>'<button type="button" data-tx="'+item.id+'" class="card '+(state.txId===item.id?"selected":"")+'"><i>'+String(item.number).padStart(2,"0")+'</i><strong>'+item.symbol+'</strong><span><b>'+item.title+'</b><small>'+item.description+'</small></span><em>'+item.mode+'</em></button>').join("");$$('[data-tx]').forEach(button=>button.addEventListener("click",()=>{state.txId=button.dataset.tx;renderDeck();$("#to-practice").disabled=false}))}
function openDeck(withSuggestion){syncField();if(withSuggestion){state.suggestion=suggestTransmission(state.tension);state.txId=state.suggestion.id;const tx=TRANSMISSIONS.find(item=>item.id===state.txId);$("#recommendation").hidden=false;$("#recommendation-copy").textContent=tx.title+" · "+state.suggestion.reason}else{$("#recommendation").hidden=true}renderDeck();$("#to-practice").disabled=!state.txId;setStage("deck")}
function openPractice(){const tx=TRANSMISSIONS.find(item=>item.id===state.txId);$("#transmission-head").innerHTML='<span>'+tx.symbol+'</span><div><small>'+tx.id+' · '+tx.mode+'</small><h2>'+tx.title+'</h2></div>';$("#question").textContent=tx.question;$("#action").textContent=tx.action;setStage("practice")}
function syncPractice(){state.voiceTrace=$("#voice-trace").value.trim();state.nextStep=$("#next-step").value.trim();state.owner=$("#owner").value.trim();state.window=$("#window").value.trim()}
function validatePractice(){syncPractice();const ignored=["OBJECT_INCOMPLETE","TENSION_INCOMPLETE","VOICES_INCOMPLETE","TRANSMISSION_REQUIRED"];const errors=validateSession(state,TRANSMISSIONS).filter(code=>!ignored.includes(code));$("#commit").disabled=errors.length>0;$("#practice-hint").textContent=errors.length?"Не завершено: "+errors.map(code=>({TRACE_INCOMPLETE:"след голосов",STEP_INCOMPLETE:"следующий шаг",OWNER_REQUIRED:"владелец",WINDOW_REQUIRED:"окно",VOICE_GATE_REQUIRED:"ворота голосов"})[code]).filter(Boolean).join(" · "):"Все явные поля заполнены · можно зафиксировать след"}
function commit(){syncPractice();state.session=buildSession(state,TRANSMISSIONS);save(state.session);renderResult(state.session);setStage("result")}
function renderResult(session){const ready=session.outcome==="ready";$("#outcome").textContent=ready?"READY":"HOLD";$("#outcome").classList.toggle("hold",!ready);$("#result-title").textContent=ready?"Передача получила наблюдаемый следующий ход.":"Передача удержана до предъявления всех голосов.";$("#result-copy").textContent=ready?"Это не решение за группу: паспорт фиксирует только названный участниками шаг.":"Записанный шаг сохранён, но поле прямо отмечено как неполное.";const rows=[["Объект",session.sharedObject],["Голоса",session.voices.join(" · ")],["Передача",session.transmission.symbol+" "+session.transmission.title],["След голосов",session.voiceTrace],["Следующий шаг",session.nextStep],["Владелец · окно",session.owner+" · "+session.window],["Хранение","локально в этом браузере"]];$("#trace").innerHTML=rows.map(([key,value])=>'<div><dt>'+key+'</dt><dd>'+escapeHtml(value)+'</dd></div>').join("")}
function exportSession(){if(!state.session)return;const blob=new Blob([JSON.stringify(state.session,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download="seven-transmissions-"+state.session.id+".json";link.click();URL.revokeObjectURL(url)}
function reset(){Object.assign(state,{object:"",tension:"",voices:"",txId:"",voiceTrace:"",nextStep:"",owner:"",window:"",voiceGate:"",session:null,suggestion:null});$$('textarea,input[type="text"],input:not([type])').forEach(input=>{input.value=""});$$('input[type="radio"]').forEach(input=>{input.checked=false});$("#recommendation").hidden=true;renderDeck();validateField();validatePractice();setStage("field")}
["#shared-object","#tension","#voices"].forEach(selector=>$(selector).addEventListener("input",validateField));["#voice-trace","#next-step","#owner","#window"].forEach(selector=>$(selector).addEventListener("input",validatePractice));$$('input[name="voice-gate"]').forEach(input=>input.addEventListener("change",()=>{state.voiceGate=input.value;validatePractice()}));$("#suggest").addEventListener("click",()=>openDeck(true));$("#open-deck").addEventListener("click",()=>openDeck(false));$("#to-practice").addEventListener("click",openPractice);$("#commit").addEventListener("click",commit);$("#restart").addEventListener("click",reset);$("#export").addEventListener("click",exportSession);
renderDeck();updateJournal();validateField();validatePractice();

if ("serviceWorker" in navigator) navigator.serviceWorker.register("../sw.js").catch(() => {});
